### ISSUE TITLE
Is this cookbook still being maintained? We're willing to adopt

### ISSUE THREAD

**Issue by gdavison** [widgit-cookbooks/nxlog#22]
Hi @gh2k, are you still maintaining this cookbook?

We make use of it, but need to update to Chef 13, and this cookbook does not work with it. If you're not maintaining it, we're willing to adopt it.

Thanks for creating the cookbook.

**Comment by ifdefined** [comment]
(very, very, very!) belatedly, this is fine, and I'm glad you went ahead and did it. The cookbook is no longer used by us, and its creator has long since left the company.
