### ISSUE TITLE
Add serverspec tests to travis

### ISSUE THREAD

**Issue by patcon** [widgit-cookbooks/nxlog#5]
Just got this set up yesterday, if you want to steal the tactic:
https://github.com/mission-impossible-android/chef-cm-update-server/blob/master/.travis.yml
https://github.com/mission-impossible-android/chef-cm-update-server#testing

Basically, the standard `.kitchen.yml` is for my local docker testing, and then I used the instructions in the readme to iron out the AWS kinks locally. The `kitchen.yml` overrides are in `.kitchen.travis.yml`, which is renamed on travis and when testing locally. The rest is just envvars (AWS_PROFILE when running ec2 tests on laptop, and individual envvars when running from travis). The one catch is generating a travis user on AWS, and giving it just enough perms to do what's needed, then including its encrypted private key in the repo (using `travis encrypt-file`) so that travis can ssh into the new AMI.

Anyhow, feel free to ask me any questions. Definitely interested in using this cookbook, and would love to see that coverage reflected in travis results :)

**Comment by gh2k** [comment]
Thanks for your interest! I haven't written about this cookbook anywhere yet so it's nice that you found it.

I considered adding EC2 (or Google Cloud as it's cheaper and easier to keep track of billing for diferent projects) but I was concerned that it was going to be awkward to get the Windows tests running. Getting the admin password is a faff and the default Windows images don't have (IIRC) ssh or winrm installed by default. 

We're using a TeamCity server in-house that has physical build agents so they can run the kitchen tests locally, but obviously the results of that aren't public or available for PRs.

I guess I could do it with just the Linuces, so I'll keep this issue open and will look at it next time I work on the cookbook. Thanks :-)

**Comment by ifdefined** [comment]
Very belatedly closing this - repo has been adopted here: https://github.com/sous-chefs/sc-nxlog
