### ISSUE TITLE
Allow for arbitrary module templates

### ISSUE THREAD

**Issue by patcon** [widgit-cookbooks/nxlog#8]
First off, thanks for making this available! Glad to find it!

Would it not be more extensible to, instead of building output and input config files dynamically (as you seem to be doing with `templates/resources/destination.conf.erb` and `templatesresources/source.conf.erb`?) to include a template for each (which is a bit more straightforward to grok imho), and create the provider such that it searches for templates based on the module name, defaulting to searching in _your_ cookbook, but could be overriden to search for a template in another wrapper cookbook. This would also save from having to accommodate the config values of each module type in the resource itself, which seems like it might be cumbersome.

```
chef-nxlog
└── templates
    └── default
        └── modules
            ├── im_dbi.erb
            ├── im_file.erb
            ├── im_kernel.erb
            ├── im_mseventlog.erb
            ├── om_blocker.erb
            ├── om_dbi.erb
            ├── om_file.erb
            ├── om_http.erb
            ├── om_null.erb
            └── om_ssl.erb
```

And a new resource for a pre-defined type might be

``` rb
nxlog_config "blahblah" do
  module "im_file"
  directives {read_from_last: true, file: "/path/to/file.log"}
end
```

So for a newly defined module type, like elasticsearch:

``` rb
nxlog_config "bar" do
  module "im_elasticsearch"
  template_cookbook "my_nxlog"
  template_source "modules/my_nxlog.erb"
  directory {bar: 42, baz: "some string"}
end
```

The ruby-style hash keys would be converted to camelcase when printed to the config.

I'm not familiar with all the module formats, but perhaps the templates could still remain dynamic (a simple template rather than one for each, like I suggested above)

Anyhow, this would make it so that someone could use this cookbook without submitting a pull request for each new module or new config of the module, which would strike me as a difficult proposition for something aspiring to be a community cookbook :)

**Comment by gh2k** [comment]
Thanks. I've been thinking about ways to add extra modules/extensions into this.

The main reason that I abstracted the LWRPs out into separate source/destination objects was to:
a) simplify the process of simple logging to a destination without having to learn a lot about nxlog internals (I want to take bunch of files a, and send them to b)
b) introduce a 'default destination' mechanism which doesn't appear in nxlog directly.

The latter is more important imho. It allows one to create an nxlog input in a cookbook without worrying about the destination, knowing it will be sent to the default outputs. This relies on some magic using defines in the config files that is sub-optimal but works. ¯\_(ツ)_/¯

One way to work around this might be to add a nxlog_extension LWRP and an additional mechanism to allow arbitrary configuration directives to be passed in to the modules. For example:
```ruby
nxlog_source "foo" do
  module "im_awesomemodule"
  custom_parameters { foo: 17, bar: "cheese" }
end
```

Would that be acceptable?

**Comment by patcon** [comment]
I'm with you, but I think I am less inclined to hide nxlog internals, and in fact, I'd love it if this cookbook allowed me to look somewhere and see things that I recognize (ie. config templates) and can evaluate as operating how I expect (or which might teach me a best-practice or two). I don't want to be ignorant of how such an important tool is working :)

Your suggestion sounds great, but I am a bit confused why a new `nxlog_extension` lwrp would be needed. Couldn't it just assume custom if the module isn't recognized in `nxlog_source` or `nxlog_destination`?

**Comment by gh2k** [comment]
No, custom_parameters should be available to everything irrespective of ```*_module``` - I was considering ```nxlog_extension``` as a mechanism for dropping in an extension config.

It may be easier to drop your own file in the extensions directory, but in keeping with the philosophy of being able to specify everything via node attributes it might be nice to say:

```ruby
nxlog_extension "csv" do
  extension "xm_csv"
  parameters {
    fields: '$id, $name, $number',
    field_types: 'integer, string, integer',
    delimiter: ','
  }
end
```
... or the equivalent json. Yielding:
```
<Extension csv1>
  Module xm_csv
  Fields $id, $name, $number
  FieldTypes integer, string, integer
  Delimiter ,
</Extension>
```

**Comment by patcon** [comment]
Ohhh... sorry, I forgot that extensions were a thing in nxlog :P I'm clearly new to it...!

**Comment by vladimirlapacek** [comment]
Second off, thanks for making this available! Glad to find it!

I must second @patcon in that the templates would provide the user what he needs, while converting the NXLog configuration language to LWRP looks little complicated. My view is that this recipe will be mostly used by people familiar with NXLog, wanting to get it up and running using Chef without the need to care about the installation paths etc. Creating the LWRPs may only force them to translate what they already have in the NXLog config into LWRPs.

**Comment by patcon** [comment]
+1 @vladimirlapacek

**Comment by ifdefined** [comment]
Very belatedly, closing this; repository has been adopted here => https://github.com/sous-chefs/sc-nxlog
